### ISSUE TITLE
Keymaps are not being loaded.

### ISSUE THREAD

**Issue by mynomoto** [xkxx/CodeMirror-VimSleek#3]
I sent a pr to the official vim plugin like the one I sent to this one. But there, ctrl+r are now working as it should, but not with this one. It's kind of strange since everything looks ok, but I'm almost certain that the keymap are not being loaded.

**Comment by xkxx** [comment]
Okay I just updated everything from upstream but it didn't seem to fix the issue. Can you confirm  that c-D and c-R are working in official Vim 0.0.4?

**Comment by mynomoto** [comment]
I can confirm that c-R works on the official Vim 0.0.4. c-D was a different patch, from another user and was not merged yet.

**Comment by xkxx** [comment]
Okay. Can you try replacing vim.keymap with the following:

``` clojure
{:+ {:find-bar.vim {"enter" [:find.hide]}
    :editor.keys.vim {"ctrl-r" [:passthrough]}
    :editor.keys.vim.normal {"ctrl-d" [:passthrough]}}}
```

And see if that fixes the issue?

On my current machine, doing this makes c-R trigger redo reliably.

**Comment by mynomoto** [comment]
It solves it. It was my mistake, sorry about that.
